const STATUS_ALIVE = 1;
const STATUS_DEAD = 0;
const DEFAULT_DIMENSION = 50;
const GAME_TICK_INTERVAL_MS = 1000;

export {
    STATUS_ALIVE,
    STATUS_DEAD,
    DEFAULT_DIMENSION,
    GAME_TICK_INTERVAL_MS,
}
